<!-- Datoteka: htdocs/partials/form_sign_up.phtml -->

<?php
    # Prije includeanja obrasca, postavlja se varijabla $formType (hrv. tip obrasca) prema kojoj se određuje naslov obrasca i action URL.
    # Ovo je potrebno zato jer se ovaj identični kod reciklira na drugoj stranici (izmjena detalja profila). Na toj stranici je obrazac u skočnoj modalnoj formi.

    $formType ??= "create";
    if ($formType === "update") {
        $formTitle = LANG["editProfile"];
        $formAction = "/app/forms/sign_up.php?update";
    }
    else {
        $formTitle = LANG["signUp"];
        $formAction = "/app/forms/sign_up.php";
    }
?>
<form action="<?=$formAction?>" method="post" class="form form-validate">

<?php if ($formType === "update"): ?>
    <!-- Gumb za zatvaranje modalnog prozora. -->
    <button type="button" data-overlay="edit-profile" class="btn btn-close-overlay">
        <i class="bi bi-x-lg"></i></button>
<?php endif; ?>

    <h1><?=$formTitle?></h1>

    <!-- Labela i polje za upis korisničkog imena. -->
    <label for="username"><?=LANG["username"]?></label>
    <!-- Prvo polje se automatski fokusira ako obrazac nije u skočnom modalnom prozoru. -->
    <input <?=$formType === "create" ? "autofocus" : null?>
        required type="text" name="username" id="username"
        pattern="<?=trim(UserModel::REGEX_VALID_USERNAME, "/")?>"
        title="<?=LANG["invalidUsername"]?>" class="input">
    <!-- pattern atribut sadržava regular expression za validaciju korisničkog imena. -->

    <label for="email"><?=LANG["email"]?></label>
    <input required type="email" name="email" id="email" class="input"
        title="<?=LANG["invalidEmail"]?>">

<?php if ($formType !== "update"): # Polje za lozinku se prikazuje samo tijekom registracije ?>
    <label for="password"><?=LANG["password"]?></label>
    <div class="input-group">
        <input required type="password" name="password" id="password"
            pattern="<?=trim(UserModel::REGEX_VALID_PASSWORD, "/")?>"
            title="<?=LANG["invalidPassword"]?>" class="input">
        <button type="button" id="btn-password-peak" class="btn">
            <i class="bi bi-eye-fill"></i>
        </button>
    </div>
<?php endif; ?>

    <label for="first-name"><?=LANG["firstName"]?></label>
    <input required type="text" name="firstName" id="first-name"
        pattern="<?=trim(UserModel::REGEX_VALID_NAME, "/")?>"
        title="<?=LANG["invalidName"]?>" class="input">

    <label for="last-name"><?=LANG["lastName"]?></label>
    <input required type="text" name="lastName" id="last-name"
        pattern="<?=trim(UserModel::REGEX_VALID_NAME, "/")?>"
        title="<?=LANG["invalidName"]?>" class="input">

    <button class="btn"><?=$formTitle?></button>

    <!-- Ovaj element sadržava povratnu informaciju korisniku (ako je došlo do neke greške). -->
    <div class="form-error-msg"><?=Util::getFormError();?></div>
</form>
<script>
<?php
# Na obrascu za izmjena detalja profila se popunjuju već postojeće vrijednosti iz baze podataka.
    if ($formType === "update") {
        foreach (UserModel::UPDATE_VARS as $inputName) {
            $var = $user->$inputName;
            echo "document.forms[0].elements['$inputName'].defaultValue = '$var';\n";
        }
    }
?>
</script>
